env:
  global:
    - COVERALLS_REPO_TOKEN=2XViaRWyaV8yRZkozfEu7pC9vPpFJAXDm
language: python
os:
  - linux
python:
  - "2.7"
script:
  - pip install coverage
  - pip install coveralls
  - coverage run -m unittest discover -s lexpy/tests
  - coverage report
  - coveralls