env:
  global:
    - COVERALLS_REPO_TOKEN=2XViaRWyaV8yRZkozfEu7pC9vPpFJAXDm
language: python
os:
  - linux
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - pip install future
  - pip install coverage
  - pip install coveralls
  - coverage run -m unittest --source lexpy/tests
  - coverage report
  - coveralls